import React from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <div className="bg-linear-to-br from-[#caf0f8]/30 via-[#90e0ef]/20 to-white py-20">
        <div className="container mx-auto px-6">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-[#0077b6] hover:text-[#03045e] mb-8 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            Back to Home
          </Link>
          <h1 className="text-5xl md:text-6xl font-bold text-[#03045e] mb-4">
            Privacy Policy
          </h1>
          <p className="text-xl text-gray-600">
            Last updated: January 22, 2025
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="container mx-auto px-6 py-16 max-w-4xl">
        <div className="prose prose-lg max-w-none">
          <p className="text-lg text-gray-700 leading-relaxed mb-8">
            This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and informs You about Your privacy rights and how the law protects You.
          </p>

          <p className="text-lg text-gray-700 leading-relaxed mb-12">
            We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          {/* Interpretation and Definitions */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Interpretation and Definitions</h2>

            <h3 className="text-2xl font-bold text-[#03045e] mb-4">Interpretation</h3>
            <p className="text-gray-700 mb-8">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning whether they appear in singular or plural.
            </p>

            <h3 className="text-2xl font-bold text-[#03045e] mb-4">Definitions</h3>
            <p className="text-gray-700 mb-4">For the purposes of this Privacy Policy:</p>

            <div className="space-y-4 mb-8">
              <div>
                <p className="text-gray-700"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote.</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Company</strong> (referred to as "the Company", "We", "Us" or "Our") refers to World Age Inno S.R.L, operating under the brand Adona Ai, Address: Bulveradul Unirii 60.</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Cookies</strong> are small files placed on Your computer, mobile device, or any other device by a website, containing details of Your browsing history.</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Country</strong> refers to: Romania</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Device</strong> means any device that can access the Service such as a computer, cellphone, or digital tablet.</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Personal Data</strong> means any information that relates to an identified or identifiable individual.</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Service</strong> refers to the Website and platform operated by Adona Ai.</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company.</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Usage Data</strong> refers to data collected automatically, generated by the use of the Service or from the Service infrastructure.</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Website</strong> refers to Adona Ai, accessible from <a href="https://adona.ai" className="text-[#0077b6] hover:underline">https://adona.ai</a></p>
              </div>
              <div>
                <p className="text-gray-700"><strong>You</strong> means the individual or legal entity accessing or using the Service.</p>
              </div>
            </div>
          </section>

          {/* Collecting and Using Your Personal Data */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Collecting and Using Your Personal Data</h2>

            <h3 className="text-2xl font-bold text-[#03045e] mb-4">Types of Data Collected</h3>

            <h4 className="text-xl font-bold text-[#03045e] mb-3">Personal Data</h4>
            <p className="text-gray-700 mb-4">While using Our Service, We may ask You to provide certain personally identifiable information, including but not limited to:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-8">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-xl font-bold text-[#03045e] mb-3">Usage Data</h4>
            <p className="text-gray-700 mb-4">Usage Data is collected automatically when using the Service and may include:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
              <li>IP address</li>
              <li>Browser type and version</li>
              <li>Pages visited</li>
              <li>Time and date of visits</li>
              <li>Time spent on pages</li>
              <li>Device identifiers and diagnostic data</li>
            </ul>

            <p className="text-gray-700 mb-8">When accessing the Service via a mobile device, additional data such as mobile device type, operating system, and mobile browser may be collected.</p>

            <h4 className="text-xl font-bold text-[#03045e] mb-3">Tracking Technologies and Cookies</h4>
            <p className="text-gray-700 mb-4">We use Cookies and similar tracking technologies to track activity and store certain information.</p>

            <p className="text-gray-700 mb-3"><strong>Types of Cookies We Use:</strong></p>
            <div className="space-y-4 mb-6">
              <div>
                <p className="text-gray-700"><strong>Necessary / Essential Cookies</strong></p>
                <p className="text-gray-700">Type: Session Cookies</p>
                <p className="text-gray-700">Purpose: Enable core functionality and account authentication</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Cookies Policy / Acceptance Cookies</strong></p>
                <p className="text-gray-700">Type: Persistent Cookies</p>
                <p className="text-gray-700">Purpose: Identify acceptance of cookies</p>
              </div>
              <div>
                <p className="text-gray-700"><strong>Functionality Cookies</strong></p>
                <p className="text-gray-700">Type: Persistent Cookies</p>
                <p className="text-gray-700">Purpose: Remember preferences such as login details or language</p>
              </div>
            </div>

            <p className="text-gray-700 mb-8">You may refuse Cookies through your browser settings; however, some parts of the Service may not function properly.</p>
          </section>

          {/* Use of Your Personal Data */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Use of Your Personal Data</h2>
            <p className="text-gray-700 mb-4">The Company may use Personal Data to:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Provide and maintain the Service</li>
              <li>Manage Your Account</li>
              <li>Perform contractual obligations</li>
              <li>Contact You regarding updates or security notices</li>
              <li>Provide marketing communications (unless opted out)</li>
              <li>Manage user requests</li>
              <li>Conduct business transfers</li>
              <li>Analyze usage and improve the Service</li>
            </ul>
          </section>

          {/* Sharing of Personal Data */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Sharing of Personal Data</h2>
            <p className="text-gray-700 mb-4">We may share Your Personal Data:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>With Service Providers</li>
              <li>During business transfers</li>
              <li>With Affiliates</li>
              <li>With business partners</li>
              <li>With other users (when shared publicly)</li>
              <li>With Your consent</li>
            </ul>
          </section>

          {/* Retention of Your Personal Data */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Retention of Your Personal Data</h2>
            <p className="text-gray-700 mb-4">
              We retain Personal Data only as long as necessary for the purposes outlined in this Privacy Policy, including legal compliance, dispute resolution, and enforcement of agreements.
            </p>
            <p className="text-gray-700">
              Usage Data is generally retained for a shorter period unless required for security or legal obligations.
            </p>
          </section>

          {/* Transfer of Your Personal Data */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Transfer of Your Personal Data</h2>
            <p className="text-gray-700">
              Your data may be processed outside Your jurisdiction. By using the Service, You consent to such transfers. We ensure adequate safeguards are in place to protect Your data.
            </p>
          </section>

          {/* Delete Your Personal Data */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Delete Your Personal Data</h2>
            <p className="text-gray-700 mb-4">You have the right to request deletion of Your Personal Data. You may:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-4">
              <li>Manage data through account settings</li>
              <li>Contact Us to request access, correction, or deletion</li>
            </ul>
            <p className="text-gray-700">We may retain certain data where legally required.</p>
          </section>

          {/* Disclosure of Your Personal Data */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Disclosure of Your Personal Data</h2>

            <h3 className="text-xl font-bold text-[#03045e] mb-4">Business Transactions</h3>
            <p className="text-gray-700 mb-6">If involved in a merger or asset sale, Your Personal Data may be transferred with prior notice.</p>

            <h3 className="text-xl font-bold text-[#03045e] mb-4">Law Enforcement</h3>
            <p className="text-gray-700 mb-6">We may disclose Personal Data if required by law.</p>

            <h3 className="text-xl font-bold text-[#03045e] mb-4">Other Legal Requirements</h3>
            <p className="text-gray-700">Disclosure may occur to comply with legal obligations or protect rights and safety.</p>
          </section>

          {/* Security of Your Personal Data */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Security of Your Personal Data</h2>
            <p className="text-gray-700">
              We use commercially reasonable measures to protect Your Personal Data. However, no method of transmission or storage is 100% secure.
            </p>
          </section>

          {/* Children's Privacy */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Children's Privacy</h2>
            <p className="text-gray-700">
              Our Service does not address individuals under the age of 13. We do not knowingly collect Personal Data from children under 13.
            </p>
          </section>

          {/* Links to Other Websites */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Links to Other Websites</h2>
            <p className="text-gray-700">
              Our Service may contain links to third-party websites. We are not responsible for their privacy practices.
            </p>
          </section>

          {/* Changes to This Privacy Policy */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Changes to This Privacy Policy</h2>
            <p className="text-gray-700">
              We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated "Last updated" date.
            </p>
          </section>

          {/* Contact Us */}
          <section className="mb-12 bg-[#caf0f8]/20 p-8 rounded-3xl border border-[#90e0ef]/30">
            <h2 className="text-3xl font-bold text-[#03045e] mb-6">Contact Us</h2>
            <p className="text-gray-700 mb-4">If you have any questions about this Privacy Policy, contact us:</p>
            <div className="space-y-2 text-gray-700">
              <p><strong>Email:</strong> <a href="mailto:adona.creative@gmail.com" className="text-[#0077b6] hover:underline">adona.creative@gmail.com</a></p>
              <p><strong>Website:</strong> <a href="https://adona.ai" className="text-[#0077b6] hover:underline">https://adona.ai</a></p>
              <p><strong>Company:</strong> World Age Inno S.R.L</p>
              <p><strong>Address:</strong> Bulveradul Unirii 60</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
